- name: pass a message on the command line
  hosts: server1
  vars: 
          greeting: "you didn't specify a message"
  tasks:
          - name: output a message
            debug: msg="{{ greeting }}"
