---

- name: set fact to simplify variable reference
  hosts: server1
  shell: >
          aws ec2 describe-snapshots --filters
  Name=tag:Name,Values=my-snapshot 
  |  jq --raw-output ".Snapshots[].SnapshotId"
  register: snap_result

- set_fact: snap={{ snap_result.stdout }}

- name: delete old snapshot
  command: aws ec2 delete-snapshot --snapshot-id "{{ snap }}"
