--- 

- name: show return value of command module
  hosts: server1
  tasks:
          - name: capture output of id command
            command: id -un
            register: login
          - debug: var=login

