apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-debugger
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: busybox-debugger
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
    # The pod template ends here
