git clone git@github.com:Valloric/YouCompleteMe.git
git clone git@github.com:gregsexton/gitv.git
git clone git@github.com:elixir-editors/vim-elixir.git
git clone git@github.com:slashmili/alchemist.vim.git
git clone git@github.com:neovimhaskell/haskell-vim.git
git clone git@github.com:vim-erlang/vim-erlang-runtime.git
git clone git@github.com:rafi/awesome-vim-colorschemes.git
git clone git@github.com:Xuyuanp/nerdtree-git-plugin.git
git clone git@github.com:posva/vim-vue.git
git clone git@github.com:eagletmt/neco-ghc.git
git clone git@github.com:vim-erlang/vim-erlang-omnicomplete.git
git clone git@github.com:derekwyatt/vim-scala.git
git clone git@github.com:tpope/vim-fireplace.git
git clone git@github.com:guns/vim-clojure-static.git
git clone git@github.com:tpope/vim-endwise.git
git clone git@github.com:vim-ruby/vim-ruby.git
git clone git@github.com:Glench/Vim-Jinja2-Syntax.git
git clone git@github.com:tpope/vim-surround.git
git clone git@github.com:ElmCast/elm-vim.git
git clone git@github.com:jelera/vim-javascript-syntax.git
git clone git@github.com:mattn/emmet-vim.git
git clone git@github.com:miyakogi/seiya.vim.git
git clone git@github.com:idris-hackers/idris-vim.git
git clone git@github.com:tfnico/vim-gradle.git
git clone git@github.com:udalov/kotlin-vim.git
git clone git@github.com:artur-shaik/vim-javacomplete2.git
git clone git@github.com:pangloss/vim-javascript.git
git clone git@github.com:dart-lang/dart-vim-plugin.git
git clone git@github.com:gleam-lang/gleam.vim.git
git clone git@github.com:fatih/vim-go.git
